spring:
  application:
     name: flight-catalogue-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: testing
        format_sql: true
    hibernate:
      ddl-auto: validate

server:
   port: '8081'
   
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
       defaultZone: http://localhost:8082/eureka